/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `record-shelf-${version}`;

// Assets generated by the build process + static files
const ASSETS = [...build, ...files];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
	);
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then((keys) =>
			Promise.all(
				keys
					.filter((key) => key !== CACHE_NAME)
					.map((key) => caches.delete(key))
			)
		)
	);
});

sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Only cache same-origin requests
	if (url.origin !== location.origin) return;

	// Skip API routes
	if (url.pathname.startsWith('/api/')) return;

	event.respondWith(
		caches.match(event.request).then((cached) => {
			// Return cached asset if available (build/static assets)
			if (cached) return cached;

			// For navigation/page requests, try network first
			return fetch(event.request).then((response) => {
				// Don't cache non-ok responses or opaque responses
				if (!response.ok) return response;

				// Cache static-looking responses for offline use
				if (ASSETS.includes(url.pathname)) {
					const clone = response.clone();
					caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
				}

				return response;
			});
		})
	);
});
